name: DEV actions
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - DEV
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run DEVflow script
        run: |
          python3 project_code/DEVflow.py > DEVout.txt
          
      # Commit the changes
      - name: Commit Changes
        run: |
          git config --global user.email "grace.poole@wipro.com"
          git config --global user.name "plainIDusecase"
          git add .
          git commit -m "Output"
      
      # Push the changes back to the repository
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
