name: DEV actions
on:
  push:
    branches:
      - DEV

jobs:
  save-output:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install requests
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Run DEVflow script
        run: |
          python3 project_code/DEVflow.py > DEVout.txt

      # Upload the output file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV-output
          path: DEVout.txt

