name: DEV actions
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - DEV
jobs:
  save-output:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run DEVflow script
        run: |
          python3 project_code/DEVflow.py > DEVout.txt
      - name: Upload Output File
        uses: actions/upload-artifact@v4
        with:
          name: DevOutput
          path: DEVout.txt
