name: DEV actions
on:
  push:
    branches:
      - DEV

jobs:
  save-output:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run DEVflow script
        run: |
          python3 project_code/DEVflow.py > DEVout.txt

      # Upload the output file as a release asset
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ secrets.UPLOAD_URL }}
          asset_path: DEVout.txt
          asset_name: DEVout.txt
          asset_content_type: text/plain

