name: Print Success on Dev Folder Commit

on:
  push:
    paths:
      - 'Dev/**' # Trigger only on changes in the Dev folder

jobs:
  print_success:
    runs-on: ubuntu-latest
    steps:
      - name: Print Success
        run: echo "Success"
   
