name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set Git Identity
        run: |
          git config --global user.email "grace.poole@wipro.com"
          git config --global user.name "plainIDusecase"
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          TEST: ${{ secrets.TEST }}
        run: python project_code/DEVflow.py

      - name: Commit Output to Another Branch
        run: |
          git checkout -b Test
          echo "Output: $OUTPUT" > output.txt
          git add output.txt
          git commit -m "Add output.txt"
          git pull origin Test --rebase  # Pull with rebase to handle divergence
          git push origin Test
        env:
          USERNAME: ${{ secrets.plainIDusecase }}
          TOKEN: ${{ secrets.PAT }}
